name: Tests
on:
  pull_request:

# This will cancel in progress jobs if another job with the same ref gets started.
# Github run_id is a backup in case github.ref doesn't exist for some reason
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  # Set this to ensure that jest does not create snapshot files if they're missing
  CI: true

jobs:
  db-checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - name: corepack
        run: |
          corepack enable
      - name: install
        run: |
          yarn install
      - name: db test
        run: |
          yarn db-test-full
